use ux::{u12, u4};

enum Instruction {
    SYS { addr: u12 },
    CLS,
    RET,
    JP { addr: u12 },
    CALL { addr: u12 },
    SEI { vx: u4, imm: u8 },
    SNEI { vx: u4, imm: u8 },
    SE { vx: u4, vy: u4 },
    LDI { vx: u4, imm: u8 },
    ADDI { vx: u4, imm: u8 },
    LD { vx: u4, vy: u4 },
    OR { vx: u4, vy: u4 },
    AND { vx: u4, vy: u4 },
    XOR { vx: u4, vy: u4 },
    ADD { vx: u4, vy: u4 },
    SUB { vx: u4, vy: u4 },
    SHR { vx: u4, vy: u4 },
    SUBN { vx: u4, vy: u4 },
    SHL { vx: u4, vy: u4 },
    SNE { vx: u4, vy: u4 },
    LDA { addr: u12 },
    JPO { addr: u12 },
    RND { vx: u4, imm: u8 },
    DRW { vx: u4, vy: u4, size: u4 },
    SKP { vx: u4 },
    SKNP { vx: u4 },
    LDDT { vx: u4 },
    LDST { vx: u4 },
    ADDIR { vx: u4 },
    LDSPR { vx: u4 },
    STR { vx: u4 },
    LDR { vx: u4 },
}
